@baseUrl = http://localhost:5218
@contentType = application/json

###
GET {{baseUrl}}/api/member

###
POST {{baseUrl}}/api/member
Content-Type: {{contentType}}

{
  "name": "Carlos Prueba",
  "email": "carlos.test@gym.com",
  "phone": "555-9999",
  "membershipTypePublicId": "a23e6a52-ab2c-44f1-bd6d-f427eb3bc29c"
}

###
POST {{baseUrl}}/api/user
Content-Type: {{contentType}}

{
  "email": "carlos.test@gym.com",
  "password": "Password123!",
  "role": "Member",
  "memberPublicId": "88c9cccb-1b7d-4a0c-a2f5-69407aec7925"
}

###
GET {{baseUrl}}/api/user/01a3ec7f-50eb-4a7e-a260-ffd4db799c9b

###
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "carlos.test@gym.com",
  "password": "Password123!"
}

###
GET {{baseUrl}}/api/user/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEzZWM3Zi01MGViLTRhN2UtYTI2MC1mZmQ0ZGI3OTljOWIiLCJlbWFpbCI6ImNhcmxvcy50ZXN0QGd5bS5jb20iLCJyb2xlIjoiTWVtYmVyIiwianRpIjoiMDAyMjE5MzEtZWVjMS00ZDk3LWJiODUtMjY1YzE5Nzc4MTIyIiwibWVtYmVyX3B1YmxpY19pZCI6Ijg4YzljY2NiLTFiN2QtNGEwYy1hMmY1LTY5NDA3YWVjNzkyNSIsIm1lbWJlcnNoaXBfYWN0aXZlIjoiZmFsc2UiLCJleHAiOjE3ODk5NjYyNTEsImlzcyI6Ikd5bU1lbWJlcnNoaXBBUEkiLCJhdWQiOiJHeW1NZW1iZXJzaGlwQ2xpZW50In0.34s3pZN0Lw0bzCof20x53FNeVJxS14LB2DUlKliwdUg

###
GET {{baseUrl}}/api/user/01a3ec7f-50eb-4a7e-a260-ffd4db799c9b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEzZWM3Zi01MGViLTRhN2UtYTI2MC1mZmQ0ZGI3OTljOWIiLCJlbWFpbCI6ImNhcmxvcy50ZXN0QGd5bS5jb20iLCJyb2xlIjoiTWVtYmVyIiwianRpIjoiMDAyMjE5MzEtZWVjMS00ZDk3LWJiODUtMjY1YzE5Nzc4MTIyIiwibWVtYmVyX3B1YmxpY19pZCI6Ijg4YzljY2NiLTFiN2QtNGEwYy1hMmY1LTY5NDA3YWVjNzkyNSIsIm1lbWJlcnNoaXBfYWN0aXZlIjoiZmFsc2UiLCJleHAiOjE3ODk5NjYyNTEsImlzcyI6Ikd5bU1lbWJlcnNoaXBBUEkiLCJhdWQiOiJHeW1NZW1iZXJzaGlwQ2xpZW50In0.34s3pZN0Lw0bzCof20x53FNeVJxS14LB2DUlKliwdUg

###
GET {{baseUrl}}/api/member
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEzZWM3Zi01MGViLTRhN2UtYTI2MC1mZmQ0ZGI3OTljOWIiLCJlbWFpbCI6ImNhcmxvcy50ZXN0QGd5bS5jb20iLCJyb2xlIjoiTWVtYmVyIiwianRpIjoiMDAyMjE5MzEtZWVjMS00ZDk3LWJiODUtMjY1YzE5Nzc4MTIyIiwibWVtYmVyX3B1YmxpY19pZCI6Ijg4YzljY2NiLTFiN2QtNGEwYy1hMmY1LTY5NDA3YWVjNzkyNSIsIm1lbWJlcnNoaXBfYWN0aXZlIjoiZmFsc2UiLCJleHAiOjE3ODk5NjYyNTEsImlzcyI6Ikd5bU1lbWJlcnNoaXBBUEkiLCJhdWQiOiJHeW1NZW1iZXJzaGlwQ2xpZW50In0.34s3pZN0Lw0bzCof20x53FNeVJxS14LB2DUlKliwdUg
